package es.deusto.ingenieria.sd.strava.client.gui.GraphicalWindows;
import javax.swing.*;

import es.deusto.ingenieria.sd.strava.client.gui.HomeWindow;
import es.deusto.ingenieria.sd.strava.client.gui.LoginDialog;
import es.deusto.ingenieria.sd.strava.server.data.dto.ChallengeDTO;
import es.deusto.ingenieria.sd.strava.server.data.dto.TrainingDTO;
import es.deusto.ingenieria.sd.strava.server.data.dto.UserDTO;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.awt.event.WindowAdapter;

public class HomeW extends JFrame{
	private JPanel principal;
	private JPanel p1;
	private JScrollPane sp;
	private JPanel p2;
	private JPanel p3;
	private JPanel p4;
	private JSpinner peso;
	private JSpinner altura;
	private JList Challenge;
	private JList Training;
	private JList GChallenge;
	private JList GTraining;
	private JLabel lName;
	private JPanel p31;
	private JPanel p32;
	private JLabel lMail;
	private JButton logoutButton;
	private JButton createChallengeButton;
	private JButton createYourSessionButton;


	private LoginDialog l;
	private HomeWindow hw;
	private UserDTO u;

	@SuppressWarnings("unchecked")
	public HomeW(UserDTO u, LoginDialog l, HomeWindow hw) {
		
		System.out.println(u.toString());
		
		this.l = l;
		this.hw = hw;
		this.u = u;
		System.out.println("Printeo usuario ±±±± "+u);
		
		$$$setupUI$$$();

		setContentPane(this.principal);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setSize(800, 600);
		pack();
		setLocationRelativeTo(null);
		setVisible(true);

		lName.setText("Hello " + u.getName() + "!");
		lMail.setText(u.getMail());

		peso.setValue(u.getWeight());
		altura.setValue(u.getHeight());

		Challenge.setAutoscrolls(true);
		Challenge.setListData(fillModelC(u.getChallenges()));
		Training.setAutoscrolls(true);		
		Training.setListData(fillModelT(u.getSessions()));
		GChallenge.setAutoscrolls(true);
		GChallenge.setListData(fillModelC(hw.getAllChallenges()));
		GTraining.setAutoscrolls(true);
		GTraining.setListData(fillModelT(hw.getAllTrainings()));



		logoutButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
				l.logout();
			}
		});

		createChallengeButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				System.out.println("Create challenge");
				//TODO VENTANA DE REGISTRO DE CHALLENGE
				SetUpChallengeW s = new SetUpChallengeW(l, hw);
			}
		});

		createYourSessionButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				System.out.println("Create session");
				CreateTrainingSessionW n = new CreateTrainingSessionW(l, hw);
			}
		});

		this.addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent e) {
				dispose();
				l.logout();
			}

		});   

	}

	private Object[] fillModelC(List<ChallengeDTO> list) {
		ArrayList<String> a = new ArrayList<>();
		for (int i = 0; i < list.size(); i++) {
			a.add(i, list.get(i).toString());
		}
		return a.toArray();
	}

	private Object[] fillModelT(List<TrainingDTO> list) {
		ArrayList<String> a = new ArrayList<>();
		for (int i = 0; i < list.size(); i++) {
			a.add(i, list.get(i).toString());
		}
		return a.toArray();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		principal = new JPanel();
		principal.setLayout(new BorderLayout(0, 0));
		principal.setAutoscrolls(true);
		principal.setMinimumSize(new Dimension(800, 800));
		principal.setPreferredSize(new Dimension(800, 600));
		p1 = new JPanel();
		p1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		principal.add(p1, BorderLayout.NORTH);
		lName = new JLabel();
		lName.setText("Welcome, User.name");
		p1.add(lName);
		sp = new JScrollPane();
		principal.add(sp, BorderLayout.CENTER);
		p2 = new JPanel();
		p2.setLayout(new GridBagLayout());
		p2.setRequestFocusEnabled(true);
		sp.setViewportView(p2);
		p3 = new JPanel();
		p3.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridheight = 2;
		gbc.weightx = 0.8;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		p2.add(p3, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Your lists");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		p3.add(label1, gbc);
		p31 = new JPanel();
		p31.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.weightx = 1.0;
		gbc.weighty = 0.5;
		gbc.fill = GridBagConstraints.BOTH;
		p3.add(p31, gbc);
		Challenge = new JList();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 2;
		gbc.weightx = 0.45;
		gbc.weighty = 0.4;
		gbc.fill = GridBagConstraints.BOTH;
		p31.add(Challenge, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.weightx = 0.1;
		gbc.weighty = 0.4;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		p31.add(spacer1, gbc);
		Training = new JList();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 1;
		gbc.gridwidth = 2;
		gbc.weightx = 0.45;
		gbc.weighty = 0.4;
		gbc.fill = GridBagConstraints.BOTH;
		p31.add(Training, gbc);
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.BOTH;
		p31.add(panel1, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Your challenges");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel1.add(label2, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(spacer2, gbc);
		createChallengeButton = new JButton();
		createChallengeButton.setText("Create challenge");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(createChallengeButton, gbc);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 4;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.BOTH;
		p31.add(panel2, gbc);
		final JLabel label3 = new JLabel();
		label3.setText("Your trainings");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel2.add(label3, gbc);
		final JPanel spacer3 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(spacer3, gbc);
		createYourSessionButton = new JButton();
		createYourSessionButton.setText("Create your session");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(createYourSessionButton, gbc);
		final JLabel label4 = new JLabel();
		label4.setText("Global lists");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		p3.add(label4, gbc);
		p32 = new JPanel();
		p32.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 7;
		gbc.weightx = 1.0;
		gbc.weighty = 0.5;
		gbc.fill = GridBagConstraints.BOTH;
		p3.add(p32, gbc);
		final JPanel spacer4 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.weightx = 0.01;
		gbc.weighty = 0.4;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		p32.add(spacer4, gbc);
		GTraining = new JList();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.weightx = 0.45;
		gbc.weighty = 0.4;
		gbc.fill = GridBagConstraints.BOTH;
		p32.add(GTraining, gbc);
		final JLabel label5 = new JLabel();
		label5.setText("Global challenges");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		p32.add(label5, gbc);
		final JLabel label6 = new JLabel();
		label6.setText("Global trainings");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		p32.add(label6, gbc);
		GChallenge = new JList();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 0.45;
		gbc.weighty = 0.4;
		gbc.fill = GridBagConstraints.BOTH;
		p32.add(GChallenge, gbc);
		final JPanel spacer5 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		p3.add(spacer5, gbc);
		final JPanel spacer6 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 6;
		gbc.fill = GridBagConstraints.VERTICAL;
		p3.add(spacer6, gbc);
		final JPanel spacer7 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.fill = GridBagConstraints.VERTICAL;
		p3.add(spacer7, gbc);
		final JPanel spacer8 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.VERTICAL;
		p3.add(spacer8, gbc);
		p4 = new JPanel();
		p4.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 0.2;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		p2.add(p4, gbc);
		final JLabel label7 = new JLabel();
		label7.setHorizontalAlignment(0);
		label7.setHorizontalTextPosition(0);
		label7.setText("Your data");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		p4.add(label7, gbc);
		final JPanel spacer9 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.VERTICAL;
		p4.add(spacer9, gbc);
		lMail = new JLabel();
		lMail.setText("Your email is user.mail");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		p4.add(lMail, gbc);
		final JLabel label8 = new JLabel();
		label8.setText("Weight");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		p4.add(label8, gbc);
		peso = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		p4.add(peso, gbc);
		altura = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		p4.add(altura, gbc);
		final JLabel label9 = new JLabel();
		label9.setText("Height");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		p4.add(label9, gbc);
		final JPanel spacer10 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		p4.add(spacer10, gbc);
		final JPanel spacer11 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.fill = GridBagConstraints.VERTICAL;
		p4.add(spacer11, gbc);
		logoutButton = new JButton();
		logoutButton.setText("Logout");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		p4.add(logoutButton, gbc);
	}

}
