# Generated by Django 3.2.8 on 2021-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammamiaApp', '0004_auto_20211204_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='name')),
                ('apellido', models.CharField(max_length=50, verbose_name='surname')),
                ('calle', models.CharField(max_length=100, verbose_name='street')),
                ('cPostal', models.IntegerField(max_length=5, verbose_name='postal code')),
                ('nTelefono', models.IntegerField(max_length=13, verbose_name='telephone number')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price')),
                ('lPizzas', models.ManyToManyField(related_name='pizzasPorPedido', to='mammamiaApp.Pizza')),
            ],
        ),
    ]
