# Generated by Django 3.2.8 on 2021-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammamiaApp', '0005_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cPostal',
            field=models.IntegerField(verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nTelefono',
            field=models.IntegerField(verbose_name='telephone number'),
        ),
    ]
