# Generated by Django 3.2.8 on 2021-12-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammamiaApp', '0006_auto_20211205_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
