# Generated by Django 3.2.8 on 2021-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammamiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='mammamiaApp.Ingrediente'),
        ),
    ]
