# Generated by Django 3.2.8 on 2021-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammamiaApp', '0002_pizza_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(related_name='pizzas', to='mammamiaApp.Ingrediente'),
        ),
    ]
