library("readxl")
library("writexl")

data <- read_excel("XLSX/data.xlsx")

#DEL SUMMARY SE PUEDE CONCLUIR EN QUE HAY QUE QUITAR LAS SIGUIENTES COLUMNAS INVALIDAS
#data$SK_ID_CURR = NULL
data$NAME_CONTRACT_TYPE = NULL
data$FLAG_MOBIL = NULL
data$REGION_RATING_CLIENT_W_CITY = NULL
data$REG_REGION_NOT_LIVE_REGION = NULL
data$REG_REGION_NOT_WORK_REGION = NULL
data$LIVE_REGION_NOT_WORK_REGION = NULL
data$REG_CITY_NOT_LIVE_CITY = NULL
data$REG_CITY_NOT_WORK_CITY = NULL
data$LIVE_CITY_NOT_WORK_CITY = NULL
data$EXT_SOURCE_1 = NULL
data$EXT_SOURCE_2 = NULL
data$EXT_SOURCE_3 = NULL
data$FLAG_OWN_CAR = NULL
data$FLAG_OWN_REALTY = NULL
data$FLAG_DOCUMENT_2 = NULL
data$FLAG_DOCUMENT_3 = NULL
data$FLAG_DOCUMENT_4 = NULL
data$FLAG_DOCUMENT_5 = NULL
data$FLAG_DOCUMENT_6 = NULL
data$FLAG_DOCUMENT_7 = NULL
data$FLAG_DOCUMENT_8 = NULL
data$FLAG_DOCUMENT_9 = NULL
data$FLAG_DOCUMENT_10 = NULL
data$FLAG_DOCUMENT_11 = NULL
data$FLAG_DOCUMENT_12 = NULL
data$FLAG_DOCUMENT_13 = NULL
data$FLAG_DOCUMENT_14 = NULL
data$FLAG_DOCUMENT_15 = NULL
data$FLAG_DOCUMENT_16 = NULL
data$FLAG_DOCUMENT_17 = NULL
data$FLAG_DOCUMENT_18 = NULL
data$FLAG_DOCUMENT_19 = NULL
data$FLAG_DOCUMENT_20 = NULL
data$FLAG_DOCUMENT_21 = NULL

data$BASEMENTAREA_AVG = NULL
data$YEARS_BEGINEXPLUATATION_AVG = NULL
data$YEARS_BUILD_AVG = NULL
data$COMMONAREA_AVG = NULL
data$ELEVATORS_AVG = NULL
data$ENTRANCES_AVG = NULL
data$FLOORSMAX_AVG = NULL
data$FLOORSMIN_AVG = NULL
data$LANDAREA_AVG = NULL
data$LIVINGAPARTMENTS_AVG = NULL
data$LIVINGAREA_AVG = NULL
data$NONLIVINGAPARTMENTS_AVG = NULL
data$NONLIVINGAREA_AVG = NULL
data$NONLIVINGAPARTMENTS_AVG = NULL
data$NONLIVINGAREA_AVG = NULL
data$APARTMENTS_MODE = NULL
data$BASEMENTAREA_MODE = NULL
data$OBS_30_CNT_SOCIAL_CIRCLE = NULL
data$OBS_60_CNT_SOCIAL_CIRCLE = NULL
data$YEARS_BEGINEXPLUATATION_MODE = NULL
data$YEARS_BUILD_MODE = NULL
data$COMMONAREA_MODE = NULL
data$ELEVATORS_MODE = NULL
data$ENTRANCES_MODE = NULL
data$FLOORSMAX_MODE = NULL
data$FLOORSMIN_MODE = NULL
data$LANDAREA_MODE = NULL
data$LIVINGAPARTMENTS_MODE = NULL
data$LIVINGAREA_MODE = NULL
data$NONLIVINGAPARTMENTS_MODE = NULL
data$NONLIVINGAREA_MODE = NULL
data$APARTMENTS_MEDI = NULL
data$BASEMENTAREA_MEDI = NULL
data$YEARS_BEGINEXPLUATATION_MEDI = NULL
data$YEARS_BUILD_MEDI = NULL
data$COMMONAREA_MEDI = NULL
data$ELEVATORS_MEDI = NULL
data$ENTRANCES_MEDI = NULL
data$FLOORSMAX_MEDI = NULL
data$FLOORSMIN_MEDI = NULL
data$LANDAREA_MEDI = NULL
data$LIVINGAPARTMENTS_MEDI = NULL
data$LIVINGAREA_MEDI = NULL
data$NONLIVINGAPARTMENTS_MEDI = NULL
data$NONLIVINGAREA_MEDI = NULL
data$FONDKAPREMONT_MODE = NULL
data$HOUSETYPE_MODE = NULL
data$TOTALAREA_MODE = NULL
data$WALLSMATERIAL_MODE = NULL
data$EMERGENCYSTATE_MODE = NULL

summary(data)

#TRATAMIENTO DE DATOS

data$CODE_GENDER[data$CODE_GENDER == 'F'] <- 0
data$CODE_GENDER[data$CODE_GENDER == 'M'] <- 1
data$CODE_GENDER <- type.convert(data$CODE_GENDER) 

data$AMT_INCOME_TOTAL <- type.convert(data$AMT_INCOME_TOTAL) 

data$AMT_CREDIT <- type.convert(data$AMT_CREDIT) 

data$AMT_ANNUITY <- type.convert(data$AMT_ANNUITY) 

data$AMT_GOODS_PRICE <- type.convert(data$AMT_GOODS_PRICE) 

data$REGION_POPULATION_RELATIVE <- type.convert(data$REGION_POPULATION_RELATIVE) 

data$DAYS_REGISTRATION <- type.convert(data$DAYS_REGISTRATION) 

data$OWN_CAR_AGE <- type.convert(data$OWN_CAR_AGE) 

data$DAYS_REGISTRATION <- type.convert(data$DAYS_REGISTRATION) 

data$CNT_FAM_MEMBERS <- type.convert(data$CNT_FAM_MEMBERS) 

data$APARTMENTS_AVG <- type.convert(data$APARTMENTS_AVG) 

data$DEF_30_CNT_SOCIAL_CIRCLE <- type.convert(data$DEF_30_CNT_SOCIAL_CIRCLE) 
data$DEF_60_CNT_SOCIAL_CIRCLE <- type.convert(data$DEF_60_CNT_SOCIAL_CIRCLE) 

data$DAYS_LAST_PHONE_CHANGE <- type.convert(data$DAYS_LAST_PHONE_CHANGE) 

data$AMT_REQ_CREDIT_BUREAU_HOUR <- type.convert(data$AMT_REQ_CREDIT_BUREAU_HOUR) 
data$AMT_REQ_CREDIT_BUREAU_DAY <- type.convert(data$AMT_REQ_CREDIT_BUREAU_DAY) 
data$AMT_REQ_CREDIT_BUREAU_WEEK <- type.convert(data$AMT_REQ_CREDIT_BUREAU_WEEK) 
data$AMT_REQ_CREDIT_BUREAU_MON <- type.convert(data$AMT_REQ_CREDIT_BUREAU_MON) 
data$AMT_REQ_CREDIT_BUREAU_QRT <- type.convert(data$AMT_REQ_CREDIT_BUREAU_QRT) 
data$AMT_REQ_CREDIT_BUREAU_YEAR <- type.convert(data$AMT_REQ_CREDIT_BUREAU_YEAR) 

data$AMT_REQ_CREDIT_BUREAU = data$AMT_REQ_CREDIT_BUREAU_HOUR + data$AMT_REQ_CREDIT_BUREAU_DAY + data$AMT_REQ_CREDIT_BUREAU_WEEK + data$AMT_REQ_CREDIT_BUREAU_MON + data$AMT_REQ_CREDIT_BUREAU_QRT + data$AMT_REQ_CREDIT_BUREAU_YEAR 
data$AMT_REQ_CREDIT_BUREAU[is.na(data$AMT_REQ_CREDIT_BUREAU)] <- 0

data$AMT_REQ_CREDIT_BUREAU_HOUR = NULL
data$AMT_REQ_CREDIT_BUREAU_DAY = NULL
data$AMT_REQ_CREDIT_BUREAU_WEEK = NULL
data$AMT_REQ_CREDIT_BUREAU_MON = NULL
data$AMT_REQ_CREDIT_BUREAU_QRT = NULL
data$AMT_REQ_CREDIT_BUREAU_YEAR  = NULL

data$DEF_CNT_SOCIAL_CIRCLE = data$DEF_30_CNT_SOCIAL_CIRCLE + data$DEF_60_CNT_SOCIAL_CIRCLE
data$DEF_CNT_SOCIAL_CIRCLE[is.na(data$DEF_CNT_SOCIAL_CIRCLE)] <- 0

data$DEF_30_CNT_SOCIAL_CIRCLE = NULL
data$DEF_60_CNT_SOCIAL_CIRCLE = NULL

data$AMT_GOODS_PRICE[is.na(data$AMT_GOODS_PRICE)] = 0 

data$DAYS_BIRTH = data$DAYS_BIRTH/365*-1
data$DAYS_BIRTH = as.integer(data$DAYS_BIRTH)

data$DAYS_EMPLOYED = data$DAYS_EMPLOYED/365*-1
data$DAYS_EMPLOYED = as.integer(data$DAYS_EMPLOYED)



summary(data)

write_xlsx(data,"XLSX/DatosLimpios.xlsx")
